#!/bin/bash
set -e

cronfile=/etc/cron.d/drupal
minute=$(expr $RANDOM % 60)

echo "PATH=/usr/src/composer/vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" > $cronfile
echo "$minute * * * * www-data drush -q -r /var/www/html cron" >> $cronfile
echo "#" >> $cronfile
cron