#!/bin/bash
set -e

cronfile=/etc/cron.d/drupal
minute=$(expr $RANDOM % 60)

echo "PATH=/var/www/scripts:/var/www/vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" > $cronfile
echo "$minute * * * * www-data drush -q -r /var/www/html --uri=$DRUPAL_URL cron" >> $cronfile
echo "#" >> $cronfile
cron